## Read in CSV file

In [5]:
import pandas as pd

denver_data = pd.read_csv('denver-1.nov.csv')  
denver_data.head()

,raw_row_number,date,time,location,lat,lng,district,precinct,type,disposition,arrest_made,citation_issued,warning_issued,outcome
0,1,2012-11-13,00:02:22,8500 W CRESTLINE AVE,39.618329,-105.092691,4,423,vehicular,K - Street Check Completed,False,False,False,NaN
1,16,2012-11-29,00:25:01,8500 W CRESTLINE AVE,39.618329,-105.092691,4,423,vehicular,Party Advised,False,False,False,NaN
2,72,2012-11-23,22:58:10,4830 S HOLLAND WAY,39.630666,-105.102551,4,423,vehicular,K - Street Check Completed,False,False,False,NaN
3,121,2012-11-27,17:48:33,4885 S QUEBEC ST,39.626174,-104.904062,3,324,pedestrian,In Service,False,False,False,NaN
4,138,2012-11-14,23:46:58,W LAYTON AVE / S WADSWORTH BLVD,39.630150,-105.081693,4,423,vehicular,Party Advised,False,False,False,NaN

## Group Data by Date

Find the total number of arrests, citations, and warnings issued each day in November. 
Drop the columns that we don't need: the raw row number and lat/long.

In [28]:
stats_daily = denver_data.groupby(['date']).sum()
stats_daily = stats_daily.drop(['raw_row_number','lat', 'lng'], axis=1)
stats_daily

            arrest_made  citation_issued  warning_issued
date
2012-11-01           44               39              27
2012-11-02           56               33              22
2012-11-03           36               42              18
2012-11-04           21               39              33
2012-11-05           25               33              18
2012-11-06           29               34              32
2012-11-07           26               30              20
2012-11-08           36               36              21
2012-11-09           23               40              26
2012-11-10           21               18              13
2012-11-11           40               36              16
2012-11-12           36               39              35
2012-11-13           44               37              41
2012-11-14           40               41              16
2012-11-15           32               39              22
2012-11-16           39               43              25
2012-11-17           43               32              19
2012-11-18           21               31              30
2012-11-19           30               38              21
2012-11-20           36               36              24
2012-11-21           30               41              26
2012-11-22           17               10              22
2012-11-23           39               29              28
2012-11-24           47               42              41
2012-11-25           27               24              16
2012-11-26           20               51              34
2012-11-27           27               30              23
2012-11-28           29               55              26
2012-11-29           36               38              17
2012-11-30           35               29              20

## Export the Data as a .json

With json, turn the dataframe into a json file using split to get the columns, data, and date (index) in the right format. Write it to a file that we can use in JS.

In [29]:
import json
import pprint as pprint

result = stats_daily.to_json(orient="split")
parsed = json.loads(result)
pprint.pprint(json.dumps(parsed, indent=4))

with open('wa8.json', 'w') as f:
    f.write(result)

('{\n'
 '    "columns": [\n'
 '        "arrest_made",\n'
 '        "citation_issued",\n'
 '        "warning_issued"\n'
 '    ],\n'
 '    "index": [\n'
 '        "2012-11-01",\n'
 '        "2012-11-02",\n'
 '        "2012-11-03",\n'
 '        "2012-11-04",\n'
 '        "2012-11-05",\n'
 '        "2012-11-06",\n'
 '        "2012-11-07",\n'
 '        "2012-11-08",\n'
 '        "2012-11-09",\n'
 '        "2012-11-10",\n'
 '        "2012-11-11",\n'
 '        "2012-11-12",\n'
 '        "2012-11-13",\n'
 '        "2012-11-14",\n'
 '        "2012-11-15",\n'
 '        "2012-11-16",\n'
 '        "2012-11-17",\n'
 '        "2012-11-18",\n'
 '        "2012-11-19",\n'
 '        "2012-11-20",\n'
 '        "2012-11-21",\n'
 '        "2012-11-22",\n'
 '        "2012-11-23",\n'
 '        "2012-11-24",\n'
 '        "2012-11-25",\n'
 '        "2012-11-26",\n'
 '        "2012-11-27",\n'
 '        "2012-11-28",\n'
 '        "2012-11-29",\n'
 '        "2012-11-30"\n'
 '    ],\n'
 '    "data": [\n'
 '        [\n'
 '            44,\n'
 '            39,\n'
 '            27\n'
 '        ],\n'
 '        [\n'
 '            56,\n'
 '            33,\n'
 '            22\n'
 '        ],\n'
 '        [\n'
 '            36,\n'
 '            42,\n'
 '            18\n'
 '        ],\n'
 '        [\n'
 '            21,\n'
 '            39,\n'
 '            33\n'
 '        ],\n'
 '        [\n'
 '            25,\n'
 '            33,\n'
 '            18\n'
 '        ],\n'
 '        [\n'
 '            29,\n'
 '            34,\n'
 '            32\n'
 '        ],\n'
 '        [\n'
 '            26,\n'
 '            30,\n'
 '            20\n'
 '        ],\n'
 '        [\n'
 '            36,\n'
 '            36,\n'
 '            21\n'
 '        ],\n'
 '        [\n'
 '            23,\n'
 '            40,\n'
 '            26\n'
 '        ],\n'
 '        [\n'
 '            21,\n'
 '            18,\n'
 '            13\n'
 '        ],\n'
 '        [\n'
 '            40,\n'
 '            36,\n'
 '            16\n'
 '        ],\n'
 '        [\n'
 '            36,\n'
 '            39,\n'
 '            35\n'
 '        ],\n'
 '        [\n'
 '            44,\n'
 '            37,\n'
 '            41\n'
 '        ],\n'
 '        [\n'
 '            40,\n'
 '            41,\n'
 '            16\n'
 '        ],\n'
 '        [\n'
 '            32,\n'
 '            39,\n'
 '            22\n'
 '        ],\n'
 '        [\n'
 '            39,\n'
 '            43,\n'
 '            25\n'
 '        ],\n'
 '        [\n'
 '            43,\n'
 '            32,\n'
 '            19\n'
 '        ],\n'
 '        [\n'
 '            21,\n'
 '            31,\n'
 '            30\n'
 '        ],\n'
 '        [\n'
 '            30,\n'
 '            38,\n'
 '            21\n'
 '        ],\n'
 '        [\n'
 '            36,\n'
 '            36,\n'
 '            24\n'
 '        ],\n'
 '        [\n'
 '            30,\n'
 '            41,\n'
 '            26\n'
 '        ],\n'
 '        [\n'
 '            17,\n'
 '            10,\n'
 '            22\n'
 '        ],\n'
 '        [\n'
 '            39,\n'
 '            29,\n'
 '            28\n'
 '        ],\n'
 '        [\n'
 '            47,\n'
 '            42,\n'
 '            41\n'
 '        ],\n'
 '        [\n'
 '            27,\n'
 '            24,\n'
 '            16\n'
 '        ],\n'
 '        [\n'
 '            20,\n'
 '            51,\n'
 '            34\n'
 '        ],\n'
 '        [\n'
 '            27,\n'
 '            30,\n'
 '            23\n'
 '        ],\n'
 '        [\n'
 '            29,\n'
 '            55,\n'
 '            26\n'
 '        ],\n'
 '        [\n'
 '            36,\n'
 '            38,\n'
 '            17\n'
 '        ],\n'
 '        [\n'
 '            35,\n'
 '            29,\n'
 '            20\n'
 '        ]\n'
 '    ]\n'
 '}')